config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#home'
  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :cost, :origin, presence: true 
  validates_length_of :name, maximum: 100 
  
  scope :three_most_recent, -> { order(created_at: :desc).limit(3)}
  scope :most_reviews, -> {(
    select("products.id, products.name, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
    )}
    scope :usa, -> { where(origin: "United States of America")}
  
  before_save(:titlelize_product)
  
  private 
    def titlelize_product
      self.name = self.name.titleize
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product

  validates :author, :presence => true
  validates :content_body, {:presence => true, :length => { :minimum => 50, :maximum => 250 }}
  validates :rating, :presence => true
  
  before_save(:titlelize_review)

  private 
    def titlelize_review
      self.author =  self.author.titleize
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :only => [:new, :edit, :create, :update, :destroy] do
  end

def index
  @products = Product.all
  render :index
end

def home
  @products = Product.all
  render :home 
end

def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews
  end

  def new
  @product = Product.new
end

def create
  @product = Product.new(product_params)
  if @product.save
    flash[:notice] = "Product successfully added!"
    redirect_to products_path
  else
    flash[:notice] = "Your product has not been added."
    render :new
  end
end

  def edit
    @product = Product.find(params[:id])
  end

  

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product successfully updated!"
      redirect_to products_path
    else
      flash[:notice] = "Your product has not been updated."
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product successfully DESTROYED!!"
    redirect_to products_path
  end

  # def landing
  #   @products = Product
  #   render :landing
  # end

  private
  def product_params
    params.require(:product).permit(:name, :cost, :origin)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :only => [:edit, :update, :destroy] do
  end

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render:new
  end
  
  def show
    @review = Review.find(params[:id])
    @product = @review.product
    render :show
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review has been successfully added"
      redirect_to product_path(@review.product)
    else
      flash[:notice] = "Your product has not been added."
      render :new
    end
  end

  def edit 
    @product = Product.find(params[:product_id])
    @review = @product.reviews.find(params[:id])
    render :edit
  end

  def update 
    @product = Product.find(params[:product_id])
    @review = @product.reviews.find(params[:id])
    if @review.update(review_params)
      flash[:notice] = "Review successfully updated!"
      redirect_to product_review_path(@product, @review)
    else
      flash[:notice] = "Your product was not added."
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "Review was successfully deleted"
    redirect_to product_path(@review.product)
  end

  private
    def review_params
      params.require(:review).permit(:author, :content_body, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Can not be left blank, please fix:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>
<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :country_of_orgin %>
  <%= f.text_field :country_of_orgin %>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MariosSpecialtyFoodProductsProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <%= flash[:alert] %>
    <%= flash[:notice] %>

    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for [ @product ] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :origin %>
  <%= f.text_field :origin %>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <%= f.submit %>
<% end %>

app/views/products/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>
<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :origin %>
  <%= f.text_field :origin %>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= render "form" %>

<p><%= link_to "Return to product", product_path(@product) %></p>

app/views/products/home.html.erb
<h1>Marios Specialty Food Products</h1>

<p><%= link_to "See the product list", products_path %></p>

  <div class="wrapper">
    <a href="?sort=recent"><button class="btn btn-default">Recently added</button></a>
    <a href="?sort=most_reviews"><button class="btn btn-default">Most Reviews</button></a>
    <a href="?sort=usa"><button class="btn btn-default">Made in United States of America</button></a>
    
    <button class="btn btn-default"><%= link_to "All Products", products_path %></button>
  </div>

<hr>
<br>
<h1>Products</h1>
  <ul>
    <% @products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
</div>
<hr>

app/views/products/index.html.erb
<h1>Products</h1>
<p><%= link_to "Return to Home", root_path %></p>
<p><%= link_to "Create new product", new_product_path %></p>

<h4>All Products</h4>
<% if @products.any? %>
  <ul>
    <% @products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no products yet please add some. </p>
<% end %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form" %>

<p><%= link_to "Return to products", products_path %></p>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h3><%= @product.origin %></h3>

<% if @product.reviews.any? %>
  <h4>Here are the reviews for this product:</h4>

  <% @product.reviews.each do |review| %>
    <ul>
      <li>
        <%= link_to review.author, product_review_path(@product, review) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No reviews yet for this product.</p>
<% end %>

<p><%= link_to "Add a review for this product", new_product_review_path(@product) %></p>

<p><%= link_to "Edit", edit_product_path(@product) %></p>
<p><%= link_to "Delete", product_path(@product),
                        :data => {:confirm => "You sure?",
                                    :method => "delete"} %></p>

<p><%= link_to "Return to products", products_path %></p>

app/views/reviews/_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_area :content_body %>
  <%= f.label :rating %>
  <%= f.number_field :rating, min: 1, max: 5 %>
  <p><%= f.submit %></p>
<% end %>

app/views/reviews/_review_form.html.erb
<%= render "layouts/errors", :object => @review %>
<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_area :content_body %>
  <%= f.label :rating %>
  <%= f.number_field :rating, min: 1, max: 5 %>
  <p><%= f.submit %></p>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit review:</h1>


<%= render "form" %>

app/views/reviews/new.html.erb
<h1>Write a Review for <%= @product.name %></h1>

<%= render "form" %>

<p><%= link_to "Return to product", product_path(@product) %></p>

app/views/reviews/show.html.erb
<h1>Author:  <%= @review.author %></h1>
<h1>Review: <%= @review.content_body %></h1>
<h1>Rating:  <%= @review.rating %></h1>

    <%= link_to "Edit Review", edit_product_review_path(@product, @review) %> |
    <%= link_to "Delete Review", product_review_path(@review),
                      :data => {
                      :method => "delete"} %>


<p><%= link_to "Return to product", product_path(@product) %></p>